/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';
export const RESET_CATEGORIES = 'RESET_CATEGORIES';
export const GET_HOTPRODUCTS = 'GET_HOTPRODUCTS';
export const GET_HOTPRODUCTS_SUCCESS = 'GET_HOTPRODUCTS_SUCCESS';
export const GET_HOTPRODUCTS_FAIL = 'GET_HOTPRODUCTS_FAIL';
export const RESET_HOTPRODUCTS = 'RESET_HOTPRODUCTS';
export const GET_ALLPRODUCTS = 'GET_ALLPRODUCTS';
export const GET_ALLPRODUCTS_SUCCESS = 'GET_ALLPRODUCTS_SUCCESS';
export const GET_ALLPRODUCTS_FAIL = 'GET_ALLPRODUCTS_FAIL';
export const RESET_ALLPRODUCTS = 'RESET_ALLPRODUCTS';
export const GET_SEARCHPRODUCTS = 'GET_SEARCHPRODUCTS';
export const GET_SEARCHPRODUCTS_SUCCESS = 'GET_SEARCHPRODUCTS_SUCCESS';
export const GET_SEARCHPRODUCTS_FAIL = 'GET_SEARCHPRODUCTS_FAIL';
export const RESET_SEARCHPRODUCTS = 'RESET_SEARCHPRODUCTS';
